export const data = [
	{
		id: 1,
		name: 'SUIS POLTRONA MENTA',
		img: './images/1.jpeg',
		price: 249,
		cat: 'POLTRONAS',
	},
	{
		id: 2,
		name: 'OEUF POLTRONA PÉROLA',
		img: './images/2.jpeg',
		price: 419,
		cat: 'POLTRONAS',
	},
	{
		id: 3,
		name: 'JUNE SOFÁ COM ARMAZENAMENTO',
		img: './images/3.jpeg',
		price: 1159,
		cat: 'CHAISE LONGUE',
	},
	{
		id: 4,
		name: 'EVRON CABECEIRA 150',
		img: './images/4.jpeg',
		price: 149,
		cat: 'CABECEIRAS',
	},
	{
		id: 5,
		name: 'LOEN ESPELHO',
		img: './images/5.jpeg',
		price: 269,
		cat: 'ESPELHOS',
	},
	{
		id: 6,
		name: 'MOEBE ESPELHO DOURADO 90X90',
		img: './images/6.jpeg',
		price: 199,
		cat: 'ESPELHOS',
	},
	{
		id: 7,
		name: 'ZAMIOCULCAS PLANTA ARTIFICIAL',
		img: './images/7.jpeg',
		price: 249,
		cat: 'PLANTAS ARTIFICIAIS',
	},
	{
		id: 8,
		name: 'BANANEIRA PLANTA ARTIFICIAL 135 CM',
		img: './images/8.jpeg',
		price: 169,
		cat: 'PLANTAS ARTIFICIAIS',
	},
	{
		id: 9,
		name: 'VINTI APARADOR CARVALHO 165',
		img: './images/9.jpeg',
		price: 869,
		cat: 'APARADORES',
	},
];
